name: PHP
on:
  pull_request:
    paths:
      - '**/*.php'
      - .github/workflows/php.yml
  push:
    paths:
      - '**/*.php'
    branches:
      - trunk
jobs:
  ecs:
    uses: shopwareLabs/actions/.github/workflows/ecs.yml@main
    with:
      extensionName: SwagPlatformDemoData
      shopwareVersion: trunk
  phpstan:
    uses: shopwareLabs/actions/.github/workflows/phpstan.yml@main
    with:
      extensionName: SwagPlatformDemoData
      shopwareVersion: trunk
  phpunit:
    strategy:
      fail-fast: false
      matrix:
        shopware-version:
          - trunk
          - 6.5.x
    uses: shopwareLabs/actions/.github/workflows/phpunit.yml@main
    with:
      extensionName: SwagPlatformDemoData
      shopwareVersion: ${{ matrix.shopware-version }}
      uploadCoverage: true
    secrets:
      codecovToken: ${{ secrets.CODECOV_TOKEN }}
